.TH CREATEBETTY "June 2022" "1.0" "Createbetty man page"
.SH NAME
Quick tool to create a c boilerplate file following Holberton school betty format
.SH SYNOPSIS
.B createbetty
[OPTIONS]
.IR name
[name]
.LP
for more details
.br
See the section \fBReferences\fR of the \fBLinux Kernel coding style\fR for more sources and references.
.LP
For more informations, please visit
.IR https://github.com/osala-eng/Betty
.SH BUGS
Please visit
.IR https://github.com/osala-eng/Betty/issues
.SH AUTHOR
Jashon OSALA, 2022
